### ISSUE TITLE
Feat - Background Task: Admin token refresh

### ISSUE THREAD

**Issue by pgmitche** [xant-tv/ecumene#2]
## Description

In order to keep admin tokens alive for reuse, an active process needs to call the Bungie API to keep refresh it.

Preferably this is achieved by a background task that is continuously active, so that users need not do this manually.

There is a placeholder `refresh_tokens` task in `EcumeneScheduler` that can be fleshed out to do this.

## Acceptance Criteria

- [x] Admin token is kept alive
- [x] Keep-alive is executed by automated background task

**Comment by pgmitche** [comment]
blocked on #11

**Comment by xant-tv** [comment]
basic `/admin register` functionality now exists - no longer blocked
