### ISSUE TITLE
Feat - Bot: /audit cog

### ISSUE THREAD

**Issue by pgmitche** [xant-tv/ecumene#5]
## Description

Through this Cog, users will be able to audit history of role-restricted commands.

This will enable users to see who ran `/admin` and `/clan` commands provided that the user also has permission to run that command themselves.

It probably only needs a few commands:
 - /audit <command> <days> (obtain audit log for that command for the last x days)
 
Return could just be in the output of a CSV file.
 - Query result -> `pandas` or something.

## Acceptance Criteria

- [x] Feature complete Cog
- [x] Respects permissions system

**Comment by xant-tv** [comment]
This functionality is complete as of `v0.5.1` - closing.
